#!/bin/sh

#
# the directory where idemeum binaries will be located
#
BINDIR=/usr/local/bin

#
# the directory where idemeum will keep its state/data
#
VARDIR=/var/lib/idemeum

[ ! $(id -u) != "0" ] || { echo "ERROR: You must be root"; exit 1; }
cd $(dirname $0)
mkdir -p $VARDIR $BINDIR
cp -f idemeum $BINDIR/ || exit 1

#
# What operating system is the user running?
#
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=linux;;
    Darwin*)    machine=darwin;;
    CYGWIN*)    machine=cygwin;;
    MINGW*)     machine=minGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

echo "idemeum binaries have been copied to $BINDIR"
echo ""
echo "Thanks for installing idemeum."
echo ""
